# Generated by Django 5.0 on 2024-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_alter_interest_image_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width of the image in pixels', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width of the image in pixels', null=True),
        ),
    ]
